version: '3.8'

services:
    mongodb:
        image: mongo:3.6
        environment:
            MONGO_INITDB_ROOT_USERNAME: forecast_user
            MONGO_INITDB_ROOT_PASSWORD: your_password2
            #MONGO_INITDB_DATABASE: ./backup:/forecast_db
        volumes:
            - ./backup:/backup

        ports:
            - 28017:27017

